services:
  - type: web
    name: college-pro-api
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        scope: build,runtime
      - key: FRONTEND_URL
        value: https://college-pro-client.vercel.app
      - key: PORT
        value: 5000
